### PR TITLE
added Ukrainian localization

### PR DESCRIPTION
**Pull request by Petro-Ivvysoft**

### CODE REVIEW

**Comment by Tjoosten** [comment]
Hey @Petro-Ivvysoft. 

Ty for your PR. can u tell me if you want this as an hackobterfest contribution. Because i only see you translated the translation files. And that's awesome but also we use translation stings on our controllers and views. 

Thats we i temporarily set this PR on hold. Feel free to contact me with any qeustions. 

Kind regards, 
Tim Joosten

**Comment by Petro-Ivvysoft** [comment]
Hey @Tjoosten 
I've reviewed your controllers and view, but don't see the need to translate anything there?
Is it possible to be more specific that still needs translation?

**Comment by Tjoosten** [comment]
Hey @Petro-Ivvysoft 

Sorry for the late answer. But imo its better to also support in the controllers and views. Because why would we translate only the basic stuff and not the whol project.

**Comment by Tjoosten** [comment]
Closing this one due inactivity

**Pull request closed without merging**
